### ISSUE TITLE
Original data access?

### ISSUE THREAD

**Issue by bhavyaac** [vikkihuangkexin/AgeAnno#1]
Hello, 
Thank you for your great work on this resource.
I am wondering where I could access the original datasets (scRNA-seq and scATAC-seq) that you have compiled in your analysis?

**Comment by vikkihuangkexin** [comment]
Hi,
The data used in our database were listed in Help function, under "Datasets" category.
Hope this would be helpful.

Thanks!

**Comment by dossantosgabrielarantes** [comment]
Still on the post's subject, is it possible to share the already processed and normalized data?

Thanks, and congratulations for the incredible paper

**Comment by vikkihuangkexin** [comment]
Thanks! Actually we tried once to put processed data in the back-end of the website and it extremely slow down the website..... So we just put the publication and assession number on the website.

**Comment by vikkihuangkexin** [comment]
> Still on the post's subject, is it possible to share the already processed and normalized data?
> 
> Thanks, and congratulations for the incredible paper

**Comment by dossantosgabrielarantes** [comment]
Would it be possible to share this file with me, by email perhaps?
I am doing some analysis, and I will probably use AgeAnno, but I would need the processed data.

My email address is arantes_gabriel@hotmail.com

Thank you very much

**Comment by vikkihuangkexin** [comment]
> Would it be possible to share this file with me, by email perhaps? I am doing some analysis, and I will probably use AgeAnno, but I would need the processed data.
> 
> My email address is [arantes_gabriel@hotmail.com](mailto:arantes_gabriel@hotmail.com)
> 
> Thank you very much

Hi,
I think it would be difficult....because the file size limit of hotmail is 10MB. Most processed expression data is larger than 10MB (like 100MB to 1000MB).
What data fomat do you need? The three files for Seuart? count matrix or expression matrix?

**Comment by dossantosgabrielarantes** [comment]
Yes, rds files would be perfect.

**Comment by dossantosgabrielarantes** [comment]
Sorry to bother you again, but do you have any news on the data?

**Comment by vikkihuangkexin** [comment]
> Sorry to bother you again, but do you have any news on the data?

Hi, 

Sorry for the late reply.
We have uploaded the rds data to the google drive. Please check whether the following link is ok to download.
Hope this would be helpful.

Google drive link:
https://drive.google.com/drive/folders/160i9KmFJ0tEYP2QBT5IjbJqhqvuu5rBW?usp=sharing

**Comment by vikkihuangkexin** [comment]
P.S.  The data for several of these organs (like heart and intestine) is placed on another server, which unfortunately has connection problem recently. We will update the remaining data as soon as it is fixed. Sorry for the inconvenience.
